defmodule MmoLiteWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :mmo_lite

  # Serve at "/mmo_lite" the static files from "priv/static" directory —
  # mounted under the project's nginx path prefix, not "/", since nginx
  # forwards the full "/mmo_lite/..." path unchanged (no stripping).
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/mmo_lite",
    from: :mmo_lite,
    gzip: not code_reloading?,
    only: MmoLiteWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug MmoLiteWeb.Router
end
